"""update invoices table

Revision ID: b5ae3ed92e39
Revises: 7ed0c138c9c3
Create Date: 2026-07-28 15:37:50.370155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ae3ed92e39'
down_revision: Union[str, Sequence[str], None] = '7ed0c138c9c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('invoices', 'supplier_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('invoices', 'supplier_nit',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('invoices', 'issue_date',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoices', 'tax',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoices', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoices', 'drive_file_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('invoices', 'drive_folder',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'drive_folder',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('invoices', 'drive_file_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('invoices', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'tax',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'issue_date',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('invoices', 'supplier_nit',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('invoices', 'supplier_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('invoices', 'invoice_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
